import Head from 'next/head'
import Navbar from '@/components/Navbar'
import ProfileHeader from '@/components/ProfileHeader'
import Socials from '@/components/Socials'
import CirclePicture from '@/components/CirclePicture'
import Skills from '@/components/Skills'


export default function Home() {
  return (
    <>
      <Head>
        <title>Jamie Catto | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className='px-5'>
          <Navbar />
          <ProfileHeader />
          <Socials />
          <CirclePicture />
        </section>

        <section className='my-8'>
          <Skills />
        </section>
      </main>
    </>
  )
}
